from __future__ import annotations

import re

EVIDENCE = ["dots", "emf5", "freezing", "orbs", "writing", "box", "uv"]

EVIDENCE_LABELS = {
    "dots": "D.O.T.S Projector",
    "emf5": "EMF Level 5",
    "freezing": "Freezing Temperatures",
    "orbs": "Ghost Orb",
    "writing": "Ghost Writing",
    "box": "Spirit Box",
    "uv": "Ultraviolet",
}

EVIDENCE_ALIASES = {
    "dots": "dots", "dot": "dots", "projector": "dots", "d.o.t.s": "dots",
    "emf": "emf5", "emf5": "emf5", "emf-5": "emf5", "emf_5": "emf5",
    "freezing": "freezing", "freeze": "freezing", "temps": "freezing", "temp": "freezing",
    "orb": "orbs", "orbs": "orbs", "ghostorb": "orbs", "ghostorbs": "orbs",
    "writing": "writing", "book": "writing",
    "box": "box", "spirit": "box", "spiritbox": "box", "spirit-box": "box",
    "uv": "uv", "ultraviolet": "uv", "fingerprints": "uv", "prints": "uv",
}

GHOST_NAMES = [
    "Aswang", "Banshee", "Dayan", "Demon", "Deogen", "Gallu", "Goryo", "Hantu", "Jinn", "Kormos",
    "Mare", "Moroi", "Myling", "Obake", "Obambo", "Oni", "Onryo", "Phantom", "Poltergeist", "Raiju",
    "Revenant", "Shade", "Spirit", "Thaye", "The Mimic", "The Twins", "Wraith", "Yokai", "Yurei",
]

GHOST_ALIASES = {re.sub(r"[^a-z0-9]", "", name.lower()): name for name in GHOST_NAMES}
GHOST_ALIASES.update({
    "mimic": "The Mimic",
    "twins": "The Twins",
    "twin": "The Twins",
    "polty": "Poltergeist",
    "polter": "Poltergeist",
    "rev": "Revenant",
    "deo": "Deogen",
})

MAP_ALIASES = {
    "unknown": "unknown",
    "tanglewood": "6 Tanglewood Drive", "6": "6 Tanglewood Drive", "6t": "6 Tanglewood Drive", "6-tanglewood": "6 Tanglewood Drive",
    "ridgeview": "10 Ridgeview Court", "10": "10 Ridgeview Court", "10r": "10 Ridgeview Court",
    "willow": "13 Willow Street", "13": "13 Willow Street", "13w": "13 Willow Street",
    "edgefield": "42 Edgefield Road", "42": "42 Edgefield Road", "42e": "42 Edgefield Road",
    "nells": "Nell's Diner", "nell": "Nell's Diner", "diner": "Nell's Diner", "nells-diner": "Nell's Diner",
    "grafton": "Grafton Farmhouse", "farmhouse": "Grafton Farmhouse",
    "woodwind": "Camp Woodwind", "camp": "Camp Woodwind", "camp-woodwind": "Camp Woodwind",
    "point": "Point Hope", "hope": "Point Hope", "point-hope": "Point Hope", "lighthouse": "Point Hope",
    "bleasdale": "Bleasdale Farmhouse",
    "restricted": "Sunny Meadows Restricted", "sunny-restricted": "Sunny Meadows Restricted", "sunny-meadows-restricted": "Sunny Meadows Restricted", "smr": "Sunny Meadows Restricted",
    "prison": "Prison",
    "maple": "Maple Lodge Campsite", "maple-lodge": "Maple Lodge Campsite", "lodge": "Maple Lodge Campsite",
    "brownstone": "Brownstone High School", "school": "Brownstone High School", "highschool": "Brownstone High School", "high-school": "Brownstone High School",
    "sunny": "Sunny Meadows Mental Institution", "sunny-meadows": "Sunny Meadows Mental Institution", "sunny-meadows-mental": "Sunny Meadows Mental Institution", "institution": "Sunny Meadows Mental Institution", "smm": "Sunny Meadows Mental Institution",
}

DIFFICULTY_ALIASES = {
    "unknown": "unknown",
    "amateur": "amateur",
    "intermediate": "intermediate",
    "pro": "professional",
    "professional": "professional",
    "nightmare": "nightmare",
    "insanity": "insanity",
    "custom": "custom",
}

WEATHER_ALIASES = {
    "unknown": "unknown",
    "sunrise": "sunrise",
    "clear": "clear",
    "fog": "fog",
    "foggy": "fog",
    "blood": "blood-moon",
    "bloodmoon": "blood-moon",
    "blood-moon": "blood-moon",
    "light-rain": "light-rain",
    "lightrain": "light-rain",
    "rain": "light-rain",
    "heavy-rain": "heavy-rain",
    "heavyrain": "heavy-rain",
    "storm": "heavy-rain",
    "wind": "windy",
    "windy": "windy",
    "snow": "snow",
    "snowy": "snow",
}

BEHAVIOR_ALIASES = {
    "40-hunt": "deogen-late-hunt",
    "active-early": "thaye-high-activity-early",
    "age": "thaye-aging-speed",
    "aggressive": "obambo-state-speed",
    "aggressive-hunt": "obambo-aggressive-hunts",
    "aging": "thaye-aging-speed",
    "airball": "oni-no-mist",
    "always-knows": "deogen-knows-location",
    "aswang": "aswang-los-ramp",
    "aswang-grace": "aswang-zero-grace",
    "aswang-hidden-spares": "aswang-hidden-spares",
    "aswang-hide": "aswang-hidden-spares",
    "aswang-los-ramp": "aswang-los-ramp",
    "aswang-speed": "aswang-los-ramp",
    "aswang-zero-grace": "aswang-zero-grace",
    "banshee-scream": "banshee-scream",
    "banshee-singing": "banshee-singing",
    "banshee-song": "banshee-singing",
    "banshee-target": "banshee-target",
    "blind-ghost": "kormos-no-los",
    "blink": "oni-full-visible",
    "blowout": "onryo-third-blowout",
    "box-alone-mismatch": "box-alone-mismatch",
    "box-condition": "box-alone-mismatch",
    "breaker": "breaker-off-direct",
    "breaker-off": "breaker-off-direct",
    "breaker-off-direct": "breaker-off-direct",
    "breaker-on": "breaker-on-benefit",
    "breaker-on-benefit": "breaker-on-benefit",
    "breaker-speed": "jinn-breaker-speed",
    "breakeroff": "breaker-off-direct",
    "breakeron": "breaker-on-benefit",
    "breathing": "deogen-spiritbox-breath",
    "bulb": "light-shatter-event",
    "bulb-burst": "light-shatter-event",
    "calm": "obambo-state-speed",
    "camdots": "goryo-camera-dots",
    "camera-dots": "goryo-camera-dots",
    "candle": "onryo-flame-prevent",
    "changing-tells": "mimic-changing-tells",
    "cold": "hantu-temperature-speed",
    "cold-breath": "hantu-breath-breaker-off",
    "cold-fast": "hantu-temperature-speed",
    "constant-throws": "polter-hunt-throw-rate",
    "crucifix-enrage": "gallu-crucifix-enraged",
    "crucifix-range": "demon-crucifix-range",
    "curse": "moroi-curse",
    "dark": "mare-lights-off",
    "dayan": "dayan-moving-speed",
    "dayan-moving": "dayan-moving-speed",
    "dayan-moving-speed": "dayan-moving-speed",
    "dayan-still": "dayan-still-slow",
    "dayan-still-slow": "dayan-still-slow",
    "deaf": "yokai-short-hearing",
    "demon-ability": "demon-ability-hunt",
    "demon-ability-hunt": "demon-ability-hunt",
    "demon-crucifix": "demon-crucifix-range",
    "demon-crucifix-range": "demon-crucifix-range",
    "demon-hunt": "demon-ability-hunt",
    "demon-short-incense": "demon-short-incense",
    "demon-smudge": "demon-short-incense",
    "deo": "deogen-distance-speed",
    "deo-breath": "deogen-spiritbox-breath",
    "deogen": "deogen-distance-speed",
    "deogen-box": "deogen-spiritbox-breath",
    "deogen-distance-speed": "deogen-distance-speed",
    "deogen-knows": "deogen-knows-location",
    "deogen-knows-location": "deogen-knows-location",
    "deogen-late-hunt": "deogen-late-hunt",
    "deogen-speed": "deogen-distance-speed",
    "deogen-spiritbox-breath": "deogen-spiritbox-breath",
    "deogen-threshold": "deogen-late-hunt",
    "different-ghost": "mimic-changing-tells",
    "disappear": "phantom-photo-disappear",
    "door": "yurei-door-room",
    "door-slam": "yurei-door-room",
    "double-interaction": "twins-double-interaction",
    "double-print": "obake-unique-print",
    "double-speed": "twins-speed-profiles",
    "early": "early-hunt",
    "early-hunt": "early-hunt",
    "electric": "raiju-electronics-speed",
    "electronics": "raiju-electronics-speed",
    "electronics-fast": "raiju-electronics-speed",
    "enraged": "gallu-state-thresholds",
    "enraged-salt": "gallu-no-salt-enraged",
    "fake-orbs": "mimic-fake-orbs",
    "fakeorb": "mimic-fake-orbs",
    "fast-accel": "aswang-los-ramp",
    "fast-los": "revenant-los-speed",
    "favorite-room": "goryo-room-stable",
    "feet-emf": "wraith-teleport",
    "fire": "onryo-flame-prevent",
    "flame": "onryo-flame-prevent",
    "footprints": "salt-footprints",
    "footsteps": "myling-quiet-footsteps",
    "freezing-breath": "hantu-breath-breaker-off",
    "full-form": "oni-full-visible",
    "fusebox-emf": "jinn-sanity-drain",
    "gallu": "gallu-state-thresholds",
    "gallu-crucifix": "gallu-crucifix-enraged",
    "gallu-crucifix-enraged": "gallu-crucifix-enraged",
    "gallu-no-salt-enraged": "gallu-no-salt-enraged",
    "gallu-nosalt": "gallu-no-salt-enraged",
    "gallu-salt": "gallu-no-salt-enraged",
    "gallu-state": "gallu-state-thresholds",
    "gallu-state-thresholds": "gallu-state-thresholds",
    "goryo": "goryo-camera-dots",
    "goryo-camera-dots": "goryo-camera-dots",
    "goryo-dots": "goryo-camera-dots",
    "goryo-room": "goryo-room-stable",
    "goryo-room-stable": "goryo-room-stable",
    "hantu": "hantu-temperature-speed",
    "hantu-breath": "hantu-breath-breaker-off",
    "hantu-breath-breaker-off": "hantu-breath-breaker-off",
    "hantu-temperature-speed": "hantu-temperature-speed",
    "head-emf": "phantom-travel",
    "hidden": "aswang-hidden-spares",
    "hidden-prints": "obake-hides-prints",
    "hiding-spot": "aswang-hidden-spares",
    "high-sanity": "early-hunt",
    "hunt": "early-hunt",
    "impossible-combo": "mimic-fake-orbs",
    "interference": "raiju-wide-interference",
    "jinn": "breaker-on-benefit",
    "jinn-breaker-speed": "jinn-breaker-speed",
    "jinn-drain": "jinn-sanity-drain",
    "jinn-los": "jinn-breaker-speed",
    "jinn-sanity-drain": "jinn-sanity-drain",
    "jinn-speed": "jinn-breaker-speed",
    "knows": "deogen-knows-location",
    "kormos": "kormos-sprint-threshold",
    "kormos-event": "kormos-no-mist-chase",
    "kormos-los": "kormos-no-los",
    "kormos-no-los": "kormos-no-los",
    "kormos-no-mist-chase": "kormos-no-mist-chase",
    "kormos-sprint": "kormos-sprint-threshold",
    "kormos-sprint-threshold": "kormos-sprint-threshold",
    "late-hunt": "deogen-late-hunt",
    "light-shatter": "light-shatter-event",
    "light-shatter-event": "light-shatter-event",
    "lights": "light-shatter-event",
    "lights-off": "mare-lights-off",
    "lights-on-roam": "mare-long-roam-lights-on",
    "lineofsight": "revenant-los-speed",
    "long-incense": "spirit-long-incense",
    "long-smudge": "spirit-long-incense",
    "look-drain": "phantom-sanity-look",
    "los-speed": "revenant-los-speed",
    "low-activity": "shade-low-interaction",
    "mare": "mare-lights-off",
    "mare-dark": "mare-lights-off",
    "mare-light-switch": "mare-no-lights-on",
    "mare-lights-off": "mare-lights-off",
    "mare-long-roam-lights-on": "mare-long-roam-lights-on",
    "mare-no-lights-on": "mare-no-lights-on",
    "mare-roam": "mare-long-roam-lights-on",
    "mimic": "mimic-fake-orbs",
    "mimic-change": "mimic-changing-tells",
    "mimic-changing-tells": "mimic-changing-tells",
    "mimic-check": "mimic-fake-orbs",
    "mimic-fake-orbs": "mimic-fake-orbs",
    "model-swap": "obake-shapeshift",
    "moroi": "moroi-curse",
    "moroi-curse": "moroi-curse",
    "moving": "dayan-moving-speed",
    "moving-speed": "dayan-moving-speed",
    "myling": "myling-quiet-footsteps",
    "myling-quiet": "myling-quiet-footsteps",
    "myling-quiet-footsteps": "myling-quiet-footsteps",
    "near-electronics": "raiju-electronics-speed",
    "no-chase-event": "kormos-no-mist-chase",
    "no-fingerprint": "obake-hides-prints",
    "no-footprints": "wraith-no-salt",
    "no-lights-on": "mare-no-lights-on",
    "no-los": "kormos-no-los",
    "no-mist": "oni-no-mist",
    "no-prints": "wraith-no-salt",
    "no-room-change": "goryo-room-stable",
    "no-salt": "wraith-no-salt",
    "no-sanity-hunt": "demon-ability-hunt",
    "nograce": "aswang-zero-grace",
    "nohunt": "shade-shy",
    "nosalt": "wraith-no-salt",
    "notphantom": "photo-visible",
    "obake": "obake-unique-print",
    "obake-hide": "obake-hides-prints",
    "obake-hides-prints": "obake-hides-prints",
    "obake-shape": "obake-shapeshift",
    "obake-shapeshift": "obake-shapeshift",
    "obake-unique-print": "obake-unique-print",
    "obambo": "obambo-state-speed",
    "obambo-aggressive-hunts": "obambo-aggressive-hunts",
    "obambo-hunt": "obambo-aggressive-hunts",
    "obambo-state-speed": "obambo-state-speed",
    "oni": "oni-no-mist",
    "oni-full-visible": "oni-full-visible",
    "oni-no-mist": "oni-no-mist",
    "oni-visible": "oni-full-visible",
    "onryo": "onryo-flame-prevent",
    "onryo-flame-prevent": "onryo-flame-prevent",
    "onryo-third-blowout": "onryo-third-blowout",
    "para": "banshee-scream",
    "parabolic": "banshee-scream",
    "phantom-drain": "phantom-sanity-look",
    "phantom-photo": "phantom-photo-disappear",
    "phantom-photo-disappear": "phantom-photo-disappear",
    "phantom-sanity-look": "phantom-sanity-look",
    "phantom-travel": "phantom-travel",
    "photo": "phantom-photo-disappear",
    "photo-disappear": "phantom-photo-disappear",
    "photo-visible": "photo-visible",
    "polter": "polter-multi-throw",
    "polter-hunt": "polter-hunt-throw-rate",
    "polter-hunt-throw-rate": "polter-hunt-throw-rate",
    "polter-multi-throw": "polter-multi-throw",
    "polter-throw": "polter-multi-throw",
    "polty": "polter-multi-throw",
    "poweroff": "breaker-off-direct",
    "poweron": "breaker-on-benefit",
    "prints": "salt-footprints",
    "quiet": "myling-quiet-footsteps",
    "raiju": "raiju-electronics-speed",
    "raiju-electronics-speed": "raiju-electronics-speed",
    "raiju-interference": "raiju-wide-interference",
    "raiju-wide-interference": "raiju-wide-interference",
    "responds": "box-alone-mismatch",
    "response": "box-alone-mismatch",
    "rev": "revenant-los-speed",
    "revenant": "revenant-los-speed",
    "revenant-los-speed": "revenant-los-speed",
    "revenant-speed": "revenant-los-speed",
    "room-trap": "yurei-incense-trap",
    "salt-footprints": "salt-footprints",
    "salt-prints": "salt-footprints",
    "saltprints": "salt-footprints",
    "same-room-block": "shade-shy",
    "sanity-drain": "jinn-sanity-drain",
    "scream": "banshee-scream",
    "shade": "shade-shy",
    "shade-activity": "shade-low-interaction",
    "shade-low-interaction": "shade-low-interaction",
    "shade-shy": "shade-shy",
    "shapeshift": "obake-shapeshift",
    "short-hearing": "yokai-short-hearing",
    "short-hunt": "obambo-aggressive-hunts",
    "short-incense": "demon-short-incense",
    "short-smudge": "demon-short-incense",
    "shy": "shade-shy",
    "singing": "banshee-singing",
    "single-target": "banshee-target",
    "six-finger": "obake-unique-print",
    "six-fingers": "obake-unique-print",
    "sixfinger": "obake-unique-print",
    "slam": "yurei-door-room",
    "slow-close": "deogen-distance-speed",
    "smudge": "spirit-long-incense",
    "song": "banshee-singing",
    "spares-hidden": "aswang-hidden-spares",
    "spirit": "spirit-long-incense",
    "spirit-long-incense": "spirit-long-incense",
    "sprint": "kormos-sprint-threshold",
    "sprinting": "kormos-sprint-threshold",
    "standing-still": "dayan-still-slow",
    "state-swap": "obambo-state-speed",
    "still": "dayan-still-slow",
    "talk-hunt": "yokai-talking-hunt",
    "talking": "yokai-talking-hunt",
    "target": "banshee-target",
    "teleport": "wraith-teleport",
    "temperature": "hantu-temperature-speed",
    "thaye": "thaye-aging-speed",
    "thaye-activity": "thaye-high-activity-early",
    "thaye-age": "thaye-aging-speed",
    "thaye-aging-speed": "thaye-aging-speed",
    "thaye-high-activity-early": "thaye-high-activity-early",
    "third-blowout": "onryo-third-blowout",
    "three-candles": "onryo-third-blowout",
    "throw": "polter-multi-throw",
    "throws": "polter-multi-throw",
    "turns-lights-off": "mare-no-lights-on",
    "twin": "twins-speed-profiles",
    "twins": "twins-speed-profiles",
    "twins-double-interaction": "twins-double-interaction",
    "twins-interaction": "twins-double-interaction",
    "twins-speed-profiles": "twins-speed-profiles",
    "two-interactions": "twins-double-interaction",
    "two-speeds": "twins-speed-profiles",
    "unique-print": "obake-unique-print",
    "visible": "oni-full-visible",
    "visible-photo": "photo-visible",
    "voice": "yokai-talking-hunt",
    "warm-room": "hantu-temperature-speed",
    "weakened": "gallu-state-thresholds",
    "wide-interference": "raiju-wide-interference",
    "wraith": "wraith-no-salt",
    "wraith-no-salt": "wraith-no-salt",
    "wraith-teleport": "wraith-teleport",
    "yokai": "yokai-talking-hunt",
    "yokai-hearing": "yokai-short-hearing",
    "yokai-short-hearing": "yokai-short-hearing",
    "yokai-talking-hunt": "yokai-talking-hunt",
    "yurei": "yurei-door-room",
    "yurei-door-room": "yurei-door-room",
    "yurei-incense": "yurei-incense-trap",
    "yurei-incense-trap": "yurei-incense-trap",
    "yurei-smudge": "yurei-incense-trap",
    "zero-grace": "aswang-zero-grace"
}

TIMER_DEFAULT_SECONDS = {
    "incense": 90,
    "hunt": 60,
    "cooldown": 25,
}

TIMER_ALIASES = {
    "smudge": "incense",
    "incense": "incense",
    "hunt": "hunt",
    "cooldown": "cooldown",
    "cd": "cooldown",
}

BEHAVIOR_INDEX_IDS = ['hantu-temperature-speed', 'raiju-electronics-speed', 'revenant-los-speed', 'deogen-distance-speed', 'dayan-moving-speed', 'dayan-still-slow', 'twins-speed-profiles', 'thaye-aging-speed', 'obambo-state-speed', 'aswang-los-ramp', 'wraith-no-salt', 'salt-footprints', 'gallu-no-salt-enraged', 'obake-unique-print', 'obake-hides-prints', 'breaker-off-direct', 'breaker-on-benefit', 'jinn-breaker-speed', 'jinn-sanity-drain', 'hantu-breath-breaker-off', 'mare-lights-off', 'mare-no-lights-on', 'light-shatter-event', 'raiju-wide-interference', 'yokai-short-hearing', 'early-hunt', 'demon-ability-hunt', 'shade-shy', 'yokai-talking-hunt', 'kormos-sprint-threshold', 'aswang-zero-grace', 'gallu-state-thresholds', 'obambo-aggressive-hunts', 'deogen-late-hunt', 'onryo-flame-prevent', 'onryo-third-blowout', 'spirit-long-incense', 'demon-short-incense', 'demon-crucifix-range', 'gallu-crucifix-enraged', 'yurei-incense-trap', 'phantom-photo-disappear', 'photo-visible', 'oni-no-mist', 'oni-full-visible', 'kormos-no-mist-chase', 'banshee-singing', 'phantom-sanity-look', 'myling-quiet-footsteps', 'banshee-scream', 'deogen-spiritbox-breath', 'moroi-curse', 'box-alone-mismatch', 'goryo-camera-dots', 'goryo-room-stable', 'thaye-high-activity-early', 'mare-long-roam-lights-on', 'yurei-door-room', 'banshee-target', 'deogen-knows-location', 'kormos-no-los', 'aswang-hidden-spares', 'wraith-teleport', 'phantom-travel', 'polter-multi-throw', 'polter-hunt-throw-rate', 'twins-double-interaction', 'shade-low-interaction', 'obake-shapeshift', 'mimic-fake-orbs', 'mimic-changing-tells']

GHOST_TESTS = {
    "Deogen": ["Hunt test: very fast far away, very slow when close.", "It always knows player location during hunts.", "Spirit Box breathing response can confirm it."],
    "Revenant": ["Hunt test: slow while searching, extremely fast after detection.", "Break line of sight and listen for deceleration."],
    "Raiju": ["Electronics test: speeds up near active electronics.", "Interference range feels wider than normal."],
    "Hantu": ["Temperature test: faster in cold rooms, slower in warm rooms.", "Freezing breath during hunts when breaker is off/broken."],
    "Wraith": ["Salt test: it never disturbs salt.", "Teleport can leave EMF near a player."],
    "Obake": ["UV test: unique fingerprints such as six fingers/double switch.", "May hide valid fingerprints or briefly shapeshift during hunts."],
    "Phantom": ["Photo test: disappears when photographed/filmed.", "More invisible during hunts; looking at it drains sanity."],
    "Poltergeist": ["Object pile test: many throws at once.", "During hunts, very high throw rate near objects."],
    "Goryo": ["D.O.T.S test: camera-only and not visible to naked eye.", "Favorite room tends to stay stable."],
    "Onryo": ["Flame test: flame prevents hunt like crucifix.", "Third flame blowout can trigger a hunt if no nearby flame remains."],
    "Spirit": ["Incense test: hunt prevention lasts much longer than normal."],
    "Demon": ["Hunt timing: can hunt very early.", "Incense protection is shorter; crucifix range is larger."],
    "The Mimic": ["Mimic check: orbs plus an impossible evidence/behavior combo.", "Behavior can change over time. Do not trust one hunt tell alone."],
    "The Twins": ["Look for two interaction locations or two hunt speeds.", "Hunt may start from extended interaction range."],
    "Yokai": ["Talking in same room can enable earlier hunts.", "During hunts, hearing range is very short."],
    "Yurei": ["Door test: strong full door close / sanity drain event.", "Incense can trap it in favorite room."],
    "Shade": ["Same-room test: low activity, no hunt/interactions while player is in same room.", "Later hunt threshold than normal."],
    "Oni": ["Event test: no mist/airball events; stronger full-form events.", "More visible during hunts."],
    "Mare": ["Light test: more dangerous in dark, avoids turning lights on.", "Can immediately turn lights off and prefers light-shatter events."],
    "Moroi": ["Curse test: sanity drains rapidly after audio/Spirit Box contact.", "Hunt speed scales with lower sanity; incense blind lasts longer."],
    "Myling": ["Sound test: footsteps/vocalizations only audible when close.", "Parabolic sounds occur more often."],
    "Banshee": ["Targeting test: focuses one player.", "Banshee scream or frequent singing events support it."],
    "Thaye": ["Aging test: starts fast/active, calms and slows over time."],
    "Jinn": ["Breaker test: fast with breaker on, line of sight, and distance.", "Can sanity-drain near fuse box; never turns breaker off directly."],
    "Kormos": ["Awareness test: no normal visual line-of-sight; reacts to sound/electronics/footsteps.", "No mist/chasing events."],
    "Aswang": ["Hunt start/speed test: possible no grace, faster line-of-sight acceleration.", "Official hiding spot behavior can spare instead of kill."],
    "Gallu": ["State test: crucifix, incense, and salt can shift normal/enraged/weakened behavior.", "Cannot disturb salt while enraged."],
    "Obambo": ["State timing test: calm/aggressive state alternates after door opens.", "Aggressive hunts earlier and can be shorter."],
    "Dayan": ["Movement test: faster if nearby player moves, slower if nearby player stands still."],
}

# Runtime compatibility exports. New gameplay content is sourced from the JSON
# registry while legacy services continue importing the established constants.
from ..content import get_registry as _get_content_registry

_content = _get_content_registry()
_evidence_items = _content.items("evidence.json")
EVIDENCE = [item["id"] for item in _evidence_items]
EVIDENCE_LABELS = {item["id"]: item["name"] for item in _evidence_items}
EVIDENCE_ALIASES = {
    alias: item["id"]
    for item in _evidence_items
    for alias in [item["id"], *item.get("aliases", [])]
}
_ghost_items = _content.ghosts
GHOST_NAMES = [item["name"] for item in _ghost_items]
GHOST_ALIASES = {
    re.sub(r"[^a-z0-9]", "", alias.lower()): item["name"]
    for item in _ghost_items
    for alias in [item["name"], *item.get("aliases", [])]
}
_map_items = _content.items("maps.json")
MAP_ALIASES = {
    alias.lower(): item["name"]
    for item in _map_items
    for alias in [item["id"], item["name"], *item.get("aliases", [])]
}
MAP_ALIASES["unknown"] = "unknown"
GHOST_TESTS["Deildegast"] = "Move many distinct objects outside a hunt, then compare its next hunt speed with an early hunt. It should slow progressively. Evidence: EMF Level 5, Ghost Writing, D.O.T.S."
